/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthenticationResult {
  'message' : string,
  'success' : boolean,
}
export interface Lead {
  'mobileNumber' : string,
  'revenueRange' : string,
  'email' : string,
  'operationalBottleneck' : string,
  'message' : string,
  'companyName' : string,
  'lastName' : string,
  'industry' : string,
  'firstName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLead' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateAdminCredentials' : ActorMethod<
    [string, string],
    AuthenticationResult
  >,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminPrivileges' : ActorMethod<[Principal], undefined>,
  'healthCheck' : ActorMethod<[], string>,
  'isAdminInitialized' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteFirstAdmin' : ActorMethod<[string], undefined>,
  'renewBootstrapToken' : ActorMethod<[], string>,
  'resetAdminSystem' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];